'use strict';

const { autoUpdater } = require('electron-updater');
const log = require('electron-log');

/**
 * Auto-update module.
 *
 * Checks for updates from the URL configured in electron-builder.yml (publish.url).
 * Downloads updates silently and installs on next app restart.
 *
 * Update files expected on the server:
 *   - ForeverKids POS Setup X.Y.Z.exe
 *   - latest.yml (generated by electron-builder)
 *
 * Host these at: https://foreverkids.dcrayons.app/pos-updates/
 */
function setupAutoUpdater(mainWindow) {
  // Log to file for debugging update issues on deployed machines
  autoUpdater.logger = log;
  autoUpdater.logger.transports.file.level = 'info';

  // Download updates automatically but don't force-install
  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;

  // Don't downgrade
  autoUpdater.allowDowngrade = false;

  autoUpdater.on('checking-for-update', () => {
    log.info('Checking for updates...');
  });

  autoUpdater.on('update-available', (info) => {
    log.info(`Update available: v${info.version}`);
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('update-available', info.version);
    }
  });

  autoUpdater.on('update-not-available', () => {
    log.info('No updates available.');
  });

  autoUpdater.on('download-progress', (progress) => {
    log.info(`Download progress: ${Math.round(progress.percent)}%`);
  });

  autoUpdater.on('update-downloaded', (info) => {
    log.info(`Update downloaded: v${info.version}. Will install on next restart.`);
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('update-downloaded', info.version);
    }
  });

  autoUpdater.on('error', (err) => {
    log.error('Auto-update error:', err.message);
  });

  // Check immediately on launch, then every 4 hours
  autoUpdater.checkForUpdatesAndNotify().catch((err) => {
    log.warn('Initial update check failed:', err.message);
  });

  setInterval(() => {
    autoUpdater.checkForUpdatesAndNotify().catch((err) => {
      log.warn('Periodic update check failed:', err.message);
    });
  }, 4 * 60 * 60 * 1000);
}

module.exports = { setupAutoUpdater };
