#!/usr/bin/env python3
"""
Foreverkids test ratchet.

Read PHPUnit's JUnit XML output, compare currently-passing tests against
a committed baseline (tests/baseline-passing.txt), and:

  * FAIL the build if any baseline test now fails (regression).
  * SUCCEED if all baseline tests still pass — even if non-baseline
    tests fail (those are tracked-as-broken).
  * Note tests that pass but aren't in the baseline yet ("free wins") so
    a developer can lock them in by adding them to the baseline.

This is the standard "test ratchet" pattern for greening up a legacy
suite without blocking delivery on full-suite green: the baseline can
only grow, never shrink, and CI guarantees no regression below it.

Usage:
    python3 scripts/ci/test_ratchet.py <junit-xml> <baseline-txt>

Bootstrap behavior:
    If <baseline-txt> doesn't exist, the script writes one from the
    current passing set and exits 0. Run this once, commit the file,
    and from then on CI enforces the ratchet.
"""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

WARN = "\033[33m"
ERR = "\033[31m"
OK = "\033[32m"
DIM = "\033[2m"
RESET = "\033[0m"


def load_results(junit_xml: Path) -> tuple[set[str], set[str]]:
    """Return (passing, failing) test name sets from a JUnit XML file.

    A test is "passing" if its <testcase> element has no <failure>,
    <error>, or <skipped> child. Skipped tests are NOT counted as
    passing — they should be either fixed or removed, not silently
    treated as green.
    """
    tree = ET.parse(junit_xml)
    passing: set[str] = set()
    failing: set[str] = set()

    for tc in tree.iter("testcase"):
        cls = tc.attrib.get("classname", "").strip()
        name = tc.attrib.get("name", "").strip()
        if not cls or not name:
            continue
        full = f"{cls}::{name}"

        has_problem = any(
            child.tag in ("failure", "error", "skipped") for child in tc
        )
        if has_problem:
            failing.add(full)
        else:
            passing.add(full)

    return passing, failing


def write_baseline(path: Path, passing: set[str]) -> None:
    """Sort + write the baseline. Sorted order keeps diffs small."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Foreverkids test ratchet baseline.\n")
        f.write("# Generated by scripts/ci/test_ratchet.py — DO NOT edit by hand.\n")
        f.write("# To add a newly-passing test, run:\n")
        f.write("#   python3 scripts/ci/test_ratchet.py <junit.xml> tests/baseline-passing.txt --update\n")
        f.write("# Tests listed here are guaranteed-passing. CI fails on regression.\n")
        f.write(f"# Count: {len(passing)}\n")
        f.write("\n")
        for name in sorted(passing):
            f.write(name + "\n")


def load_baseline(path: Path) -> set[str]:
    """Read baseline file, ignoring comments and blank lines."""
    out: set[str] = set()
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            out.add(line)
    return out


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(__doc__)
        return 2

    junit_path = Path(argv[1])
    baseline_path = Path(argv[2])
    update_mode = "--update" in argv[3:]

    if not junit_path.exists():
        print(f"{ERR}ERROR{RESET}: JUnit file not found: {junit_path}")
        return 2

    passing, failing = load_results(junit_path)
    total = len(passing) + len(failing)

    print(f"{DIM}── Test ratchet ──{RESET}")
    print(f"  JUnit:    {junit_path}")
    print(f"  Baseline: {baseline_path}")
    print(f"  Total tests:    {total}")
    print(f"  Passing:        {len(passing)}")
    print(f"  Failing:        {len(failing)}")
    print()

    # ── Bootstrap or update mode ───────────────────────────────────────────
    if not baseline_path.exists() or update_mode:
        write_baseline(baseline_path, passing)
        action = "Updated" if update_mode else "Bootstrapped"
        print(f"{WARN}{action}{RESET} baseline at {baseline_path} with {len(passing)} passing tests.")
        print()
        if not update_mode:
            print(f"{WARN}⚠  Until this file is committed to git, CI is NOT enforcing the regression gate.{RESET}")
            print(f"{WARN}⚠  Download the artifact, commit {baseline_path}, push.{RESET}")
        return 0

    # ── Compare mode ───────────────────────────────────────────────────────
    baseline = load_baseline(baseline_path)
    regressions = baseline - passing  # in baseline but not currently passing
    new_green = passing - baseline  # passing but not in baseline yet

    print(f"  Baseline size:  {len(baseline)}")
    print()

    exit_code = 0

    if regressions:
        print(f"{ERR}❌ REGRESSION — {len(regressions)} test(s) were green and now fail:{RESET}")
        for name in sorted(regressions):
            print(f"   - {name}")
        print()
        print(f"   Either fix the test, or — if you intentionally removed/renamed it —")
        print(f"   run scripts/ci/test_ratchet.py with --update to refresh the baseline.")
        print()
        exit_code = 1
    else:
        print(f"{OK}✓ No regressions. All {len(baseline)} baseline tests still pass.{RESET}")

    if new_green:
        print()
        print(f"{OK}🎉 {len(new_green)} test(s) now passing but not yet in baseline:{RESET}")
        for name in sorted(new_green)[:25]:
            print(f"   + {name}")
        if len(new_green) > 25:
            print(f"   ... and {len(new_green) - 25} more")
        print()
        print(f"   {DIM}To lock in the gain, run scripts/ci/test_ratchet.py with --update{RESET}")

    if failing - regressions:
        # Tests currently failing that are NOT regressions (i.e. expected-broken)
        expected_broken = failing - regressions
        print()
        print(f"{DIM}── {len(expected_broken)} test(s) failing as expected (not in baseline) ──{RESET}")

    return exit_code


if __name__ == "__main__":
    sys.exit(main(sys.argv))
